### PR TITLE
Fixes #4711 - add a namespace configuration option to KCF

### LINKED ISSUE #4711: Namespace errors from k8s client when namespace not set
## Environment details:

* local deployment - standalone jar
* kubernetes versions:
```
{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

## Steps to reproduce the issue:

1.   Configure the invoker to use KCF
1.   Create a service user without access to the `--all-namespaces` / `default` namespace via RBAC
1.   Use a kubeconfig that doesn't have a namespace set and uses the service user token

## Provide the expected results and outputs:
Prewarm Containers should start.

## Provide the actual results and outputs:
Prewarm containers don't start and the invoker isn't even listed in: `http://<controller_host_port>/invokers`.

```
[2019-11-04T12:33:26.826Z] [ERROR] Namespace not specified. But operation requires namespace.
io.fabric8.kubernetes.client.KubernetesClientException: Namespace not specified. But operation requires namespace.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.checkNamespace(OperationSupport.java:172)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:233)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:796)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:326)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:322)
	at org.apache.openwhisk.core.containerpool.kubernetes.KubernetesClient.run(KubernetesClient.scala:121)
	at org.apache.openwhisk.core.containerpool.kubernetes.KubernetesContainer$.create(KubernetesContainer.scala:72)
	at org.apache.openwhisk.core.containerpool.kubernetes.KubernetesContainerFactory.createContainer(KubernetesContainerFactory.scala:80)
	at org.apache.openwhisk.core.containerpool.ContainerFactory.createContainer(ContainerFactory.scala:100)
	at org.apache.openwhisk.core.containerpool.ContainerFactory.createContainer$(ContainerFactory.scala:92)
	at org.apache.openwhisk.core.containerpool.kubernetes.KubernetesContainerFactory.createContainer(KubernetesContainerFactory.scala:41)
	at org.apache.openwhisk.core.invoker.InvokerReactive.$anonfun$childFactory$2(InvokerReactive.scala:198)
	at org.apache.openwhisk.core.invoker.InvokerReactive.$anonfun$childFactory$2$adapted(InvokerReactive.scala:198)
	at org.apache.openwhisk.core.containerpool.ContainerProxy$$anonfun$1.applyOrElse(ContainerProxy.scala:277)
	at org.apache.openwhisk.core.containerpool.ContainerProxy$$anonfun$1.applyOrElse(ContainerProxy.scala:249)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at akka.actor.FSM.processEvent(FSM.scala:706)
	at akka.actor.FSM.processEvent$(FSM.scala:703)
	at org.apache.openwhisk.core.containerpool.ContainerProxy.processEvent(ContainerProxy.scala:224)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:700)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:694)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at org.apache.openwhisk.core.containerpool.ContainerProxy.aroundReceive(ContainerProxy.scala:224)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:610)
	at akka.actor.ActorCell.invoke(ActorCell.scala:579)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

### PR DESCRIPTION
**Pull request by mcdan**
A fix for #4711 

## Description
This change forces the k8s client to use a particular namespace when communicating with the API server. 

## Related issue and scope

- [X] I opened an issue to propose and discuss this change (#4711)

## My changes affect the following components

- [ ] API
- [ ] Controller
- [ ] Message Bus (e.g., Kafka)
- [ ] Loadbalancer
- [X] Invoker
- [ ] Intrinsic actions (e.g., sequences, conductors)
- [ ] Data stores (e.g., CouchDB)
- [ ] Tests
- [ ] Deployment
- [ ] CLI
- [ ] General tooling
- [ ] Documentation

## Types of changes

- [X] Bug fix (generally a non-breaking change which closes an issue).
- [ ] Enhancement or new feature (adds new functionality).
- [ ] Breaking change (a bug fix or enhancement which changes existing behavior).

## Checklist:

- [X] I signed an [Apache CLA](https://github.com/apache/openwhisk/blob/master/CONTRIBUTING.md).
- [X] I reviewed the [style guides](https://github.com/apache/openwhisk/wiki/Contributing:-Git-guidelines#code-readiness) and followed the recommendations (Travis CI will check :).
- [ ] I added tests to cover my changes.
- [ ] My changes require further changes to the documentation.
- [ ] I updated the documentation where necessary.

### CODE REVIEW

File: core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala [hunk 1]
```diff
@@ -76,6 +76,7 @@ case class KubernetesClientConfig(timeouts: KubernetesClientTimeoutConfig,
                                   invokerAgent: KubernetesInvokerAgentConfig,
                                   userPodNodeAffinity: KubernetesInvokerNodeAffinity,
                                   portForwardingEnabled: Boolean,
+                                  actionNamespace: Option[String] = None,
```
Comment (chetanmeh) [inline core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala]: Would be helpful to have a comment in application.conf explaining this optional config

https://github.com/apache/openwhisk/blob/f3040925aa408a0b32dd4f542c815a638a797cc4/core/invoker/src/main/resources/application.conf#L65-L67

Comment (mcdan) [reply core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala]: Ah thanks, I hunted around for a markdown that describes the conf settings -- didn't think to peak there. Nice catch.

File: core/invoker/src/main/resources/application.conf [hunk 2]
```diff
@@ -87,6 +86,10 @@ whisk {
     #  2. OR yaml formatted multi line string. See multi line config support https://github.com/lightbend/config/blob/master/HOCON.md#multi-line-strings
     #
     #pod-template =
+
+    # Set this optiona string to be the namespace that the invoker should target for adding pods. This allows the invoker to run in a namesapce it doesn't have API access to but add pods to another namespace. See also https://github.com/apache/openwhisk/issues/4711
```
Comment (chetanmeh) [inline core/invoker/src/main/resources/application.conf]: Nit `optiona` -> `optional`

Also explain the default behaviour when this is not configured i.e. actions pod would be launched in current invoker pods namespace

File: core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala [hunk 3]
```diff
@@ -93,10 +94,15 @@ class KubernetesClient(
     with ProcessRunner {
   implicit protected val ec = executionContext
   implicit protected val am = ActorMaterializer()
+  protected val configBuilder = new ConfigBuilder()
```
Comment (chetanmeh) [inline core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/kubernetes/KubernetesClient.scala]: As `configBuilder` is not to be used further we can avoid making it a instance field. So we can refactor this a bit via

```scala
    val builder = new ConfigBuilder()
      .withConnectionTimeout(config.timeouts.logs.toMillis.toInt)
      .withRequestTimeout(config.timeouts.logs.toMillis.toInt)
    config.actionNamespace.foreach(builder.withNamespace)
    new DefaultKubernetesClient(builder.build())
  }
```
